name: SFC Data Spine — PL (smoke)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: read
  actions: read

concurrency:
  group: sfc-spine-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Single entrypoint run
        run: |
          python scripts/sfc_pl_runner.py

      - name: Archive executed notebook & JSON
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sfc-spine-executed-${{ github.run_number }}
          path: |
            notebooks/executed_01_data_spine_pl.ipynb
            data/processed/verification_report.json
            data/processed/qc_summary.json
            logs/sfc_pl_runner.log

      - name: Archive Parquet outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sfc-spine-parquets-${{ github.run_number }}
          path: |
            data/processed/*.parquet
          if-no-files-found: warn

